# Generated by Django 4.2.23 on 2025-07-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Phone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("brand", models.CharField(max_length=100)),
                ("source_url", models.URLField()),
                ("chipset", models.CharField(blank=True, max_length=100, null=True)),
                ("gpu", models.CharField(blank=True, max_length=100, null=True)),
                ("soc_score", models.IntegerField(blank=True, null=True)),
                ("ram_gb", models.FloatField(blank=True, null=True)),
                ("storage_gb", models.FloatField(blank=True, null=True)),
                ("battery_mah", models.IntegerField(blank=True, null=True)),
                ("display_in", models.FloatField(blank=True, null=True)),
                ("refresh_hz", models.IntegerField(blank=True, null=True)),
                ("ppi", models.IntegerField(blank=True, null=True)),
                ("charging_w", models.IntegerField(blank=True, null=True)),
                ("main_mp", models.IntegerField(blank=True, null=True)),
                ("front_mp", models.IntegerField(blank=True, null=True)),
                ("res_w", models.IntegerField(blank=True, null=True)),
                ("res_h", models.IntegerField(blank=True, null=True)),
                ("bt_ver", models.FloatField(blank=True, null=True)),
                ("has_nfc", models.BooleanField(null=True)),
                ("has_fast_charging", models.BooleanField(null=True)),
                ("has_5g", models.BooleanField(null=True)),
                ("has_wireless_charging", models.BooleanField(null=True)),
                ("has_reverse_wireless_charging", models.BooleanField(null=True)),
                ("has_ois", models.BooleanField(null=True)),
                ("has_stereo_speakers", models.BooleanField(null=True)),
                ("has_aptx", models.BooleanField(null=True)),
                ("has_ldac", models.BooleanField(null=True)),
                ("price_sgd", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price_url", models.URLField()),
                ("scraped_at", models.DateTimeField()),
            ],
        ),
    ]
