# Generated by Django 4.2.23 on 2025-07-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phones", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="phone",
            name="warranty",
            field=models.CharField(default="Unknown", max_length=10),
        ),
    ]
