# Generated by Django 4.2.23 on 2025-08-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phones", "0002_phone_warranty"),
    ]

    operations = [
        migrations.AddField(
            model_name="phone",
            name="camera_main_mp",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="phone",
            name="glass_type",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="phone",
            name="ip_rating",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="phone",
            name="mohs",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
