# Generated by Django 4.2.23 on 2025-08-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phones", "0003_phone_camera_main_mp_phone_glass_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="phone",
            name="android_version",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="phone",
            name="display_type",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="phone",
            name="has_telephoto",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="phone",
            name="thickness_mm",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="phone",
            name="weight_g",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
