# Generated by Django 4.2.23 on 2026-01-30 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("phones", "0004_phone_android_version_phone_display_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="phone", name="has_telephoto",),
    ]
